---
# 26 is the maximum of slots

# permisson: NULL
enderchest-slots-default: 5

# permisson: enderchest.yt.perm
enderchest-slots-yt: 4

# permisson: enderchest.vip.perm
enderchest-slots-vip: 4

# permisson: enderchest.vip+.perm
enderchest-slots-vip+: 3

# permisson: enderchest.staff.perm
enderchest-slots-staff: 1

...
