---
# 26 is the maximum of slots

# permisson: NULL
enderchest-slots-default: 5

# permisson: enderchest.yt.perm
enderchest-slots-yt: 6

# permisson: enderchest.vip.perm
enderchest-slots-vip: 7

# permisson: enderchest.vip+.perm
enderchest-slots-vip+: 8

# permisson: enderchest.staff.perm
enderchest-slots-staff: 26

...
